### PR TITLE
Fix ZookeeperElectionServiceTest.assertContend failed for travis-ci

### LINKED ISSUE #1659: ZookeeperElectionServiceTest.assertContend fail for travis-ci
## Bug Report

 ZookeeperElectionServiceTest.assertContend fail for travis-ci
https://travis-ci.org/github/apache/shardingsphere-elasticjob/builds/736780103
https://travis-ci.org/github/apache/shardingsphere-elasticjob/builds/738211225

### PR DESCRIPTION
**Pull request by wwj-go**
Fixes #1659.

Changes proposed in this pull request:
- ZookeeperElectionServiceTest.assertContend

### CODE REVIEW

File: elasticjob-infra/elasticjob-registry-center/src/test/java/org/apache/shardingsphere/elasticjob/reg/zookeeper/ZookeeperElectionServiceTest.java [hunk 1]
```diff
@@ -29,9 +29,12 @@
 import org.junit.Test;
 import org.junit.runner.RunWith;
 import org.mockito.Mock;
+import org.mockito.internal.verification.VerificationModeFactory;
```
Comment (TeslaCN) [inline elasticjob-infra/elasticjob-registry-center/src/test/java/org/apache/shardingsphere/elasticjob/reg/zookeeper/ZookeeperElectionServiceTest.java]: Should we use the Class defined under package `internal`?
Maybe using `org.mockito.Mockito#atLeastOnce` is better.

**Review by TeslaCN — CHANGES_REQUESTED** [review]

File: elasticjob-infra/elasticjob-registry-center/src/test/java/org/apache/shardingsphere/elasticjob/reg/zookeeper/ZookeeperElectionServiceTest.java (hunk 1 above)
Comment (wwj-go) [reply elasticjob-infra/elasticjob-registry-center/src/test/java/org/apache/shardingsphere/elasticjob/reg/zookeeper/ZookeeperElectionServiceTest.java]: you are right, I will correct it.
