### PR TITLE
Maven install throw exception

### LINKED ISSUE #1035: Maven install throw exception
When run `mvn install` it throw exception,  but install result is success:

```
Tests run: 5, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.063 sec - in org.apache.shardingsphere.elasticjob.cloud.executor.TaskExecutorThreadTest
[ERROR] 2020-07-13 00:29:32,953 --test_job@-@0@-@READY@-@fake_slave_id@-@0_Worker-1-- [org.quartz.core.JobRunShell] Job DEFAULT.test_job threw an unhandled Exception:  
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at com.google.common.util.concurrent.MoreExecutors$Application.addShutdownHook(MoreExecutors.java:223)
	at com.google.common.util.concurrent.MoreExecutors$Application.addDelayedShutdownHook(MoreExecutors.java:195)
	at com.google.common.util.concurrent.MoreExecutors$Application.getExitingExecutorService(MoreExecutors.java:179)
	at com.google.common.util.concurrent.MoreExecutors$Application.getExitingExecutorService(MoreExecutors.java:214)
	at com.google.common.util.concurrent.MoreExecutors.getExitingExecutorService(MoreExecutors.java:148)
	at org.apache.shardingsphere.elasticjob.infra.concurrent.ElasticJobExecutorService.createExecutorService(ElasticJobExecutorService.java:52)
	at org.apache.shardingsphere.elasticjob.infra.handler.threadpool.impl.AbstractJobExecutorServiceHandler.createExecutorService(AbstractJobExecutorServiceHandler.java:32)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:75)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:63)
	at org.apache.shardingsphere.elasticjob.cloud.executor.DaemonTaskScheduler$DaemonJob.execute(DaemonTaskScheduler.java:182)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[ERROR] 2020-07-13 00:29:32,955 --test_job@-@0@-@READY@-@fake_slave_id@-@0_Worker-1-- [org.quartz.core.ErrorLogger] Job (DEFAULT.test_job threw an exception. 
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at com.google.common.util.concurrent.MoreExecutors$Application.addShutdownHook(MoreExecutors.java:223)
	at com.google.common.util.concurrent.MoreExecutors$Application.addDelayedShutdownHook(MoreExecutors.java:195)
	at com.google.common.util.concurrent.MoreExecutors$Application.getExitingExecutorService(MoreExecutors.java:179)
	at com.google.common.util.concurrent.MoreExecutors$Application.getExitingExecutorService(MoreExecutors.java:214)
	at com.google.common.util.concurrent.MoreExecutors.getExitingExecutorService(MoreExecutors.java:148)
	at org.apache.shardingsphere.elasticjob.infra.concurrent.ElasticJobExecutorService.createExecutorService(ElasticJobExecutorService.java:52)
	at org.apache.shardingsphere.elasticjob.infra.handler.threadpool.impl.AbstractJobExecutorServiceHandler.createExecutorService(AbstractJobExecutorServiceHandler.java:32)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:75)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:63)
	at org.apache.shardingsphere.elasticjob.cloud.executor.DaemonTaskScheduler$DaemonJob.execute(DaemonTaskScheduler.java:182)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
```

### PR DESCRIPTION
**Pull request by Technoboy-**
Fixes #1035.

### CODE REVIEW

**Comment by Technoboy-** [comment]
Comment:
As DaemonTaskSchedulerTest runs assertJobRunWithEventSampling,  job executes with registering a shutdown hook thread every time.  This will add a lot of hook threads as the job runs. While quartz schedules the job but the JVM shutdowns, job will execute failed as register shutdown hook throw IllegalStateException.

**Comment by Technoboy-** [comment]
image

File: elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/DaemonTaskScheduler.java [hunk 1]
```diff
@@ -156,10 +156,27 @@ public static void shutdown(final Protos.TaskID taskID) {
...
         private ExecutorDriver executorDriver;
-    
+        
         @Setter
         private Protos.TaskID taskId;
         
+        private ElasticJobExecutor jobExecutor;
+        
+        private ElasticJobExecutor getJobExecutor() {
+            if (null == jobExecutor) {
```
Comment (terrymanu) [inline elasticjob-cloud/elasticjob-cloud-executor/src/main/java/org/apache/shardingsphere/elasticjob/cloud/executor/DaemonTaskScheduler.java:166]: It is necessary to consider about thread safe

**Review by terrymanu — CHANGES_REQUESTED** [review]

**Review by terrymanu — APPROVED** [review]
