### PR TITLE
Trim suffix of lambda class name when using lambda expression implementation of ElasticJob

### LINKED ISSUE #1551: Using lambda implementation of interface SimpleJob may cause job conflict exception
### Actual behavior

```
Exception in thread "main" org.apache.shardingsphere.elasticjob.infra.exception.JobConfigurationException: Job conflict with register center. The job 'lambda-simple' in register center's class is 'org.apache.shardingsphere.elasticjob.lite.example.once.LambdaMain$$Lambda$7/542365801', your job class is 'org.apache.shardingsphere.elasticjob.lite.example.once.LambdaMain$$Lambda$8/542365801'
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.checkConflictJob(ConfigurationService.java:86)
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.setUpJobConfiguration(ConfigurationService.java:70)
	at org.apache.shardingsphere.elasticjob.lite.internal.setup.SetUpFacade.setUpJobConfiguration(SetUpFacade.java:66)
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobScheduler.<init>(JobScheduler.java:87)
	at org.apache.shardingsphere.elasticjob.lite.api.bootstrap.impl.ScheduleJobBootstrap.<init>(ScheduleJobBootstrap.java:41)
	at org.apache.shardingsphere.elasticjob.lite.example.once.LambdaMain.main(LambdaMain.java:47)
```

### Example codes for reproduce this issue (such as a github link).
```java
        SimpleJob simpleJob = System.out::println;
        new ScheduleJobBootstrap(REGISTRY_CENTER, simpleJob,
                JobConfiguration.newBuilder("lambda-simple", 3)
                        .cron("0/5 * * * * ?")
                        .shardingItemParameters("0=Beijing,1=Shanghai,2=Guangzhou")
                        .jobErrorHandlerType("log")
                        .overwrite(true)
                        .build(),
                TRACING_CONFIGURATION)
                .schedule();
```

### Reason analyze (If you can)
Lambda expression will be converted to a synthetic class. The class name is not fixed and it may be different each startup.

### PR DESCRIPTION
**Pull request by TeslaCN**
Fixes #1551 .

Changes proposed in this pull request:
- Rename SimpleJobClassNameProvider to DefaultJobClassNameProvider.
- Trim suffix of lambda class name when using lambda expression implementation of ElasticJob.

### CODE REVIEW

File: elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/DefaultJobClassNameProvider.java [hunk 1]
```diff
@@ -22,10 +22,20 @@
 /**
  * Simple job class name provider.
  */
-public final class SimpleJobClassNameProvider implements JobClassNameProvider {
+public final class DefaultJobClassNameProvider implements JobClassNameProvider {
     
     @Override
     public String getJobClassName(final ElasticJob elasticJob) {
```
Comment (Technoboy-) [inline elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/DefaultJobClassNameProvider.java:28]: It's better to add test case to cover this.

File: elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/DefaultJobClassNameProvider.java [hunk 2]
```diff
@@ -22,10 +22,20 @@
...
-        return elasticJob.getClass().getName();
+        Class<? extends ElasticJob> elasticJobClass = elasticJob.getClass();
+        String elasticJobClassName = elasticJobClass.getName();
+        return isLambdaClass(elasticJobClass) ? trimLambdaClassSuffix(elasticJobClassName) : elasticJobClassName;
+    }
+    
+    private boolean isLambdaClass(final Class<? extends ElasticJob> elasticJobClass) {
```
Comment (Technoboy-) [inline elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/DefaultJobClassNameProvider.java:34]: Add test case to cover this.

Comment (TeslaCN) [reply elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/setup/DefaultJobClassNameProvider.java:34]: Testcase will be committed in a new PR.

**Review by terrymanu — APPROVED** [review]
