### PR TITLE
Trigger one-off job via Zookeeper

### LINKED ISSUE #1456: OneOffJobBootstrap is only executed on invoker node
### Which version of ElasticJob did you use?
master
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite
### Expected behavior
Execution of OneOffJobBootstrap is distributed.
### Actual behavior
Only the shards which belong to invoker node will be executed. Other shards will not be executed.
### Reason analyze (If you can)
Only the invoker node has the trigger.
### Steps to reproduce the behavior.
Execute a OneOffJob only multi-node cluster.

### PR DESCRIPTION
**Pull request by TeslaCN**
Fixes #1456 .

Changes proposed in this pull request:
- Trigger one-off job via Zookeeper

### CODE REVIEW

File: elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/impl/OneOffJobBootstrap.java [hunk 1]
```diff
@@ -57,7 +59,15 @@ public OneOffJobBootstrap(final CoordinatorRegistryCenter regCenter, final Strin
      */
     public void execute() {
         Preconditions.checkArgument(Strings.isNullOrEmpty(jobScheduler.getJobConfig().getCron()), "Cron should be empty.");
-        jobScheduler.getJobScheduleController().executeJob();
+        triggerAllInstancesManually();
+    }
+    
+    private void triggerAllInstancesManually() {
```
Comment (Technoboy-) [inline elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/api/bootstrap/impl/OneOffJobBootstrap.java]: triggerAllInstancesManually -> triggerAllInstances is much more better ?

**Comment by Technoboy-** [comment]
cc @terrymanu

**Review by terrymanu — APPROVED** [review]
