### PR TITLE
Fix  spring namespace example for job-error-handler

### LINKED ISSUE #1607: Fix example for job-error-handler
Fix examples for:

- [x] Spring boot starter
- [x] Spring namespace

### PR DESCRIPTION
**Pull request by gzdzss**
For #1607.

Changes proposed in this pull request:
- [ ] Spring boot starter
- [x] Spring namespace

### CODE REVIEW

File: elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-namespace/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/namespace/job/parser/JobBeanDefinitionParser.java [hunk 1]
```diff
@@ -82,21 +82,26 @@ private BeanDefinition createJobConfigurationBeanDefinition(final Element elemen
...
     
+    private Collection<BeanDefinition> parseExtraConfigs(final String[] extraConfigRefs, final Element element, final ParserContext parserContext) {
+        Collection<BeanDefinition> extraConfigs = new ManagedList<>(extraConfigRefs.length);
+        for (String each : extraConfigRefs) {
+            String attribute = element.getAttribute(each);
+            if (!Strings.isNullOrEmpty(attribute)) {
+                extraConfigs.add(parserContext.getRegistry().getBeanDefinition(attribute));
+            }
+        }
+        return extraConfigs;
```
Comment (terrymanu) [inline elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-namespace/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/namespace/job/parser/JobBeanDefinitionParser.java]: Return value should be name as `result`

**Review by terrymanu — CHANGES_REQUESTED** [review]

**Review by Technoboy- — APPROVED** [review]
LGTM

**Review by terrymanu — APPROVED** [review]
