### PR TITLE
Close dataSource in RDBJobEventStorageTest when each test finishes

### LINKED ISSUE #1837: Flaky unit tests in RDBJobEventStorageTest(non-idempotent)
### Expected behavior
Tests `io.elasticjob.lite.event.rdb.JobEventRdbStorageTest.assertAddJobStatusTraceEventWhenFailoverWithTaskFailedState` and `io.elasticjob.lite.event.rdb.JobEventRdbStorageTest.assertAddJobStatusTraceEventWhenFailoverWithTaskStagingState` should be idempotent and pass when running twice in the same JVM

### Actual behavior
The two tests are not idempotent and fail if run twice in the same JVM
### Reason analyze (If you can)
Each of the tests pollutes some states shared among tests, causing the second test run to fail for assertions on the storage's `JobStatusTraceEvent`. For instance, the second run of `JobEventRdbStorageTest.assertAddJobStatusTraceEventWhenFailoverWithTaskFailedState` fails for the following assertion:

```
List<JobStatusTraceEvent> jobStatusTraceEvents = storage.getJobStatusTraceEvents("fake_failed_failover_task_id");
assertThat(jobStatusTraceEvents.size(), is(2));
```
### Steps to reproduce the behavior.
Run each of the aforementioned tests twice in the same JVM. The second test run would fail.

### PR DESCRIPTION
**Pull request by lzx404243**
Fixes #1837.

Changes proposed in this pull request:
-  Add a `teardown()` function to close `dataSource` in `RDBJobEventStorageTest` when each test finishes.

With the proposed fix, the test does not pollute the shared state (and passes when run twice in the same JVM).

### CODE REVIEW

File: elasticjob-ecosystem/elasticjob-tracing/elasticjob-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/tracing/rdb/storage/RDBJobEventStorageTest.java [hunk 1]
```diff
@@ -38,17 +39,24 @@
...
+        dataSource = new BasicDataSource();
         dataSource.setDriverClassName(org.h2.Driver.class.getName());
         dataSource.setUrl("jdbc:h2:mem:job_event_storage");
         dataSource.setUsername("sa");
         dataSource.setPassword("");
         storage = new RDBJobEventStorage(dataSource);
     }
     
+    @After
+    public void teardown() throws SQLException{
```
Comment (TeslaCN) [inline elasticjob-ecosystem/elasticjob-tracing/elasticjob-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/tracing/rdb/storage/RDBJobEventStorageTest.java]: Thanks for your contribution!
Please fix the checkstyle.

**Review by TeslaCN — CHANGES_REQUESTED** [review]

File: elasticjob-ecosystem/elasticjob-tracing/elasticjob-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/tracing/rdb/storage/RDBJobEventStorageTest.java (hunk 1 above)
Comment (lzx404243) [reply elasticjob-ecosystem/elasticjob-tracing/elasticjob-tracing-rdb/src/test/java/org/apache/shardingsphere/elasticjob/tracing/rdb/storage/RDBJobEventStorageTest.java]: Thanks for reviewing! The checkstyle is fixed.

**Review by TeslaCN — APPROVED** [review]
